export enum ContentType {
    JSON = "application/json",
    FORM = "application/x-www-form-urlencoded",
    MULTIPART = "multipart/form-data",
    TEXT = "text/plain",
    HTML = "text/html",
    XML = "application/xml",
    JAVASCRIPT = "application/javascript",
    CSS = "text/css",
    CSV = "text/csv",
    PDF = "application/pdf",
    OCTET_STREAM = "application/octet-stream",
    ZIP = "application/zip",
    PNG = "image/png",
    JPEG = "image/jpeg",
    GIF = "image/gif",
    SVG = "image/svg+xml",
    WEBP = "image/webp",
    MP4 = "video/mp4",
    MP3 = "audio/mpeg"
}
